### ISSUE TITLE
Mislabeled categories in plots 

### ISSUE THREAD

**Issue by dbar344** [iNZightVIT/iNZightMR#7]
The categories on the x-axis seem to be alphabetically sorted while the bars of the plots are not. 

Reproducible example:

Using the census.at.school example data from Multiple Response module, plot variables `techtv`, `techinternet` `techfacebook` `techtwitter` `techskype` and subset on `age`.
![image](https://user-images.githubusercontent.com/16076593/32035663-37c6bc34-ba77-11e7-9410-f2caf0b76d49.png)

However, by comparing the summary, this doesn't seem to make sense as facebook and internet are the opposite, i.e. 80% of 6-11 year olds have internet from the summary compared to 30% in the graph; vice versa for facebook:
```
Proportions:

        internet facebook skype    tv twitter
(6,11]     0.804    0.309 0.451 0.369   0.068
(11,13]    0.887    0.700 0.537 0.432   0.153
(13,14]    0.918    0.851 0.549 0.452   0.197
(14,19]    0.923    0.884 0.590 0.471   0.204
--------------------------------------------------------
```

Removing facebook also makes internet jump back up to 80% for 6-11 year olds:
![image](https://user-images.githubusercontent.com/16076593/32035814-1b1f225a-ba78-11e7-9ada-187e193370b1.png)

In general the problem seems to be that it alphabetically sorts the x-axis category labels, but not the order of the actual bars.

**Comment by tmelliott** [comment]
Ah yes. I think the bars are being ordered decreasing, but the labels aren't picking up on this. Somehow need to tell [this line](https://github.com/iNZightVIT/iNZightMR/blob/master/R/barplot.R#L35) about it ...
